DinnerDeals/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.login.models import User
from apps.recipes.models import Recipes, Ingredients

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(User, UAdmin)

class RecipeAdmin(admin.ModelAdmin):
    pass
admin.site.register(Recipes, RecipeAdmin)

class IngredientAdmin(admin.ModelAdmin):
    pass
admin.site.register(Ingredients, IngredientAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^user/', include('apps.recipes.urls', namespace='user')),
    url(r'^shop/', include('apps.shopping.urls', namespace='shop')),
    url(r'^main/', include('apps.recipes.urls', namespace='recipes')),
    url(r'^', include('apps.login.urls', namespace='login')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.splash, name='splash'),
    url(r'^login_page$', views.login_page, name='login_page'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^create_user$', views.create_user, name='create_user'),
    url(r'^edit_user$', views.edit_user, name='edit_user'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/recipes/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.splash, name='splash'),
    url(r'^my_account/$', views.myaccount, name='myaccount'),
    url(r'^add_recipe/$', views.add_recipe, name='add_recipe'),
    url(r'^create_recipe/$', views.create_recipe, name='create_recipe'),
    url(r'^init$', views.first_time, name='first'),
    url(r'^new$', views.new, name='new'),
    url(r'^user/(?P<u_id>\d+)$', views.user, name='userrecipes'),
    url(r'^userfavs/(?P<u_id>\d+)$', views.user_favs, name='userfavs'),
    url(r'^user/view_recipe/(?P<r_id>\d+)/$', views.view_recipe, name='view_recipe'),
    url(r'^user/button/(?P<button>\d+)/(?P<r_id>\d+)/$', views.buttons, name='buttons'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^top_fav/$', views.top_fav, name='top_fav'),
    ]

apps/shopping/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.search, name='search'),
    url(r'^zipsearch$', views.zipsearch, name='zipsearch'),
    url(r'^store$', views.store, name='found'),
    url(r'^multi$', views.multi, name='multi'),
    url(r'^displayrecipe$', views.displaysingle, name='single'),


] 

apps/recipes/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models
import re

# Create your models here.

class IngredientManager(models.Manager):
    def addIngredient(self,i_name,i_id):
        Ingredients.objects.create(name=i_name,itemid=i_id)
        return True

# In order to add ingredients to recipe, must pass an array of product ids
class RecipeManager(models.Manager):
    def newRecipe(self,postdata, u_id, ingdata, unitdata):
        if postdata['dire'] == '' and postdata['desc'] == '':
            recipe=Recipes.objects.create(title=str(postdata["title"]),units=unitdata, author=User.objects.get(id=u_id))
        elif postdata['dire'] == '':
            recipe=Recipes.objects.create(title=str(postdata["title"]),units=unitdata, author=User.objects.get(id=u_id),desc=postdata['desc'])
        elif postdata['desc'] == '':
            recipe=Recipes.objects.create(title=str(postdata["title"]),units=unitdata, author=User.objects.get(id=u_id), dire=postdata['dire'])
        else:
            recipe=Recipes.objects.create(title=str(postdata["title"]),units=unitdata, author=User.objects.get(id=u_id), dire=postdata['dire'] ,desc=postdata['desc'])
        print ingdata
        for item in ingdata:
            print item
            item=re.sub("u'"," ",item)
            ing=Ingredients.objects.get(name=str(item))
            # Try changing to objects.get_or_create()

            recipe.ingredients.add(ing)
            recipe.save()
        if 'private' in postdata:
            recipe.isprivate=True
            recipe.save()
        return True
    def deleteRecipe(self,r_id):
        Recipes.objects.get(id=r_id).delete()
        return True
    def updateRecipe(self,r_id,formdata,ingdata):
        recipe=Recipes.objects.get(id=r_id)
        recipe.title=data.title
        recipe.ingredients={}
        for item in ingdata:
            ing=Ingredients.objects.get(itemid=item)
            recipe.ingredients.add(ing)
            recipe.save()
        return True

class Recipes(models.Model):
    title=models.CharField(max_length=40)
    author=models.ForeignKey('login.User', related_name='recipe_author')
    ingredients=models.ManyToManyField('Ingredients', related_name='recipe_ing')
    desc=models.TextField(default='No discription entered.')
    dire=models.TextField(default='Throw it together and hope for the best.')
    favorites=models.ManyToManyField('login.User', related_name='favs')
    units=models.TextField(default="{ 'ing': 'Nothing?', 'qty': 'Nothing', 'unit':'Nothing' }")
    top_favorites=models.ManyToManyField('login.User', related_name='top_favs')
    isprivate=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects=RecipeManager()

class Ingredients(models.Model):
    name=models.CharField(max_length=100)
    itemid=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects=IngredientManager()

apps/recipes/views.py
from django.shortcuts import render, redirect, render_to_response
from . import init
from .models import Recipes, Ingredients
from ..login.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.db.models import Count
import json
import ast
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def first_time(request):
    if 'user' not in request.session:
        return redirect(request, 'login:')
    if not request.session['user']['id'] == 1:
        return redirect(reverse('recipes:splash'))
    init.startup()
    print 'Initalization successful'
    messages.success(request, 'Successfully Initalized!')
    return redirect(reverse('recipes:splash'))

def new(request):
    return render(request, 'recipes:new.html')

def create_recipe(request):
    if not request.method == 'POST':
        return redirect(reverse('recipse:splash'))
    ingdata=[]
    unitdata=[]
    count=int(request.POST['hidden'])
    print request.POST['item1']
    for i in range(1, count+1):
        ing=request.POST['item'+str(i)]
        nqty=request.POST['qty'+str(i)]
        nunit=request.POST['unit'+str(i)]
        print ing
        ingdata.append(ing)
        unitdata.append({'ing': ing,'qty': nqty ,'unit': nunit})
    recipe=Recipes.objects.newRecipe(request.POST, request.session['user']['id'],ingdata, unitdata)
    messages.success(request, request.POST['title']+' added successfully.')
    return redirect('recipes:add_recipe')

def splash(request):


    context={
    'recipes':Recipes.objects.filter(top_favorites=User.objects.filter(id=request.session['user']['id'])[0])

    }
    return render (request, 'recipes/splash.html', context)
def myaccount(request):
    context={
    'user':User.objects.get(id=request.session['user']['id']),
    'recipes':Recipes.objects.filter(author=request.session['user']['id']).exclude(top_favorites=User.objects.get(id=request.session['user']['id'])) | Recipes.objects.filter(favorites=request.session['user']['id']).exclude(top_favorites=User.objects.get(id=request.session['user']['id'])).order_by('title'),
    'top_fav':Recipes.objects.filter(top_favorites=User.objects.filter(id=request.session['user']['id'])[0])
    }
    return render (request, 'recipes/myaccount.html', context)
def top_fav(request,):
    user=User.objects.get(id=request.session['user']['id'])
    if user.top_favs:

        print user.top_favs
        user.top_favs.clear()
    if 'item1' in request.POST:
        user.top_favs.add(Recipes.objects.get(id=request.POST['item1']))
    if 'item2' in request.POST:
        user.top_favs.add(Recipes.objects.get(id=request.POST['item2']))
    if  'item3' in request.POST:
        user.top_favs.add(Recipes.objects.get(id=request.POST['item3']))
    messages.success(request,'Successfully changed Top favorites')
    return redirect ('recipes:myaccount')
def add_recipe(request):
    context={
    'ingredients':Ingredients.objects.distinct().order_by('name'),
    }
    return render (request, 'recipes/add_recipe.html', context)

def user(request, u_id):
    recipe=Recipes.objects.filter(author=User.objects.filter(id=u_id)[0]).order_by('-created_at')
    context={
    'user':User.objects.filter(id=u_id)[0],

    }
    pagination(request, recipe, context)
    return render(request, 'recipes/user.html', context)
def user_favs(request, u_id):
    recipe=Recipes.objects.filter(favorites=User.objects.filter(id=u_id)[0]).order_by('-created_at')
    context={
    'user':User.objects.filter(id=u_id)[0],

    }
    pagination(request, recipe, context)
    return render(request, 'recipes/user_favs.html', context)
def view_recipe(request,r_id):
    context={
    'recipe':Recipes.objects.filter(id=r_id).annotate(tot_ing=Count('ingredients'))[0],
    'user':User.objects.filter(id=request.session['user']['id'])[0],
    }
    rep=context['recipe'].units
    rep=ast.literal_eval(rep)
    print rep
    context.update({'rep':rep,})
    return render (request, 'recipes/view_recipe.html', context)
def browse(request):
    context={
    'user':User.objects.filter(id=request.session['user']['id'])[0],
    'hot':Recipes.objects.exclude(isprivate=True).annotate(num_favs=Count('favorites')).order_by('-num_favs')[:3]
    }
    recipe=Recipes.objects.exclude(isprivate=True).order_by('-created_at')
    pagination(request, recipe, context)
    print context
    return render(request, "recipes/browse.html", context)
def buttons(request, button, r_id):
    recipe= Recipes.objects.filter(id=r_id)[0]
    if button=='1':
        recipe.favorites.add(User.objects.get(id=request.session['user']['id']))
        messages.success(request,'Successfully added to favorites')
    elif button=='2':
        recipe.favorites.remove(User.objects.get(id=request.session['user']['id']))
        messages.success(request,'Successfully removed from favorites')
    elif button=='3':
        recipe.isprivate='True'
        recipe.save()
        messages.success(request,'Successfully made recipe private.')
    elif button=='4':
        recipe.isprivate='False'
        recipe.save()
        messages.success(request,'Successfully made recipe public.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
def pagination(request, recipe, context):
    paginator = Paginator(recipe, 2)
    page = request.GET.get('page')
    try:
        recipes = paginator.page(page)
    except PageNotAnInteger:
        recipes = paginator.page(1)
    except EmptyPage:
        recipes = paginator.page(paginator.num_pages)

    context.update({'recipes':recipes,'page':page})

    return(request, context)

apps/recipes/templates/recipes/base.html
<!DOCTYPE html>
<html lang ='en'>
  <head>
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% load staticfiles %}
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'recipes/css/main.css' %}"media="screen" title="no title"  charset="utf-8">
<link rel="stylesheet" href="{% static 'recipes/css/main.css' %}"media="screen" title="no title"  charset="utf-8">



    <title>Dinner Deals</title>
  </head>
  <body style='padding-top: 70px;' }>
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" >
  <div class="container"><!-- Nav tabs -->
<ul class="nav navbar-nav">
  {%block home%}<li><a href="{% url 'recipes:splash' %}">Home</a></li>{%endblock%}
  {%block shop%}<li><a href="{% url 'shop:search'%}" >Go Shopping</a></li>{%endblock%}
  {%block recipe%}<li><a href="{% url 'recipes:add_recipe'%}">Add a Recipe</a></li>{%endblock%}
  {%block myrecipe%}<li><a href="{% url 'recipes:userrecipes' u_id=request.session.user.id %}">My Recipes</a> {% endblock %}
  {%block browse%}<li><a href="{% url 'recipes:browse' %}">Browse</a> {% endblock %}
  {%block account%}<li><a href="{% url 'recipes:myaccount' %}" >My Account</a></li>{%endblock%}

  <li><a class='.navbar-right'href="{% url 'login:logout'%}" >Logout</a></li>

</ul>


  </div>
</nav>
  <p class="navbar-text"> </p>
    {%if messages%}
    {%for message in messages%}
    <li class="alert alert-{{message.tags}}" role="alert">{{message}}</li>
    {%endfor%}
    {%endif%}
  {%block content%}{%endblock%}
  {%block js%}{%endblock%}
  </body>
</html>

apps/recipes/templates/recipes/browse.html
{% extends 'recipes/base.html'%} {%block browse%}
<li class='active'><a href="{% url 'recipes:userrecipes' u_id=request.session.user.id %}">Browse</a></li>
{%endblock%}
 {%block content%}
 {% if page < '2' %}
 <h2>Whats Hot!</h2>
 {%if hot%}
 {%for recipe in hot%}
 <div class="panel panel-default panel panel-primary" style="width:70%;">
     <div class="panel-heading">
         <h3 class="panel-title" style='display:inline-block;'><a href="{% url 'recipes:view_recipe' recipe.id %}">{{recipe.title}}</a></h3><button type="button" class="btn btn-default btn-xs col-md-offset-1">
   <span class="glyphicon glyphicon-star" aria-hidden="true"></span>{{recipe.favorites.all |length}}
 </button>
         <h3 class="panel-title pull-right" style='display:inline-block;'><a href="{% url 'recipes:userrecipes' recipe.author.id %}">Created By: {{recipe.author.u_name}}</a></h3>
     </div>
     <div class="panel-body">
         <h5>Description: </h5>
         <p class='col-md-offset-1'>{{recipe.desc}}</p>
         <h6 class='col-md-offset-10'>
     {% if recipe.isprivate == True %}
     This Recipe is private.
     {%endif%}</h6> {%if user not in recipe.favorites.all%}
         <a href="{% url 'recipes:buttons' button=1 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
   <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Add to Favs
 </button></a> {%else%}
         <a href="{% url 'recipes:buttons' button=2 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
   <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Remove from  Favs
   </button></a> {%endif%} {%if request.session.user.id == recipe.author.id%}

         <a href="{% url 'recipes:buttons' button=3 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
   <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Make Private
 </button></a>
         <a href="{% url 'recipes:buttons' button=4 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
 <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Make Public
 </button></a> {%endif%}

     </div>
 </div>
 {%endfor%} {%endif%}
 {%endif%}
<h2>Browse Recipes!</h2>
{%if recipes%}
{%for recipe in recipes%}
<div class="panel panel-default panel panel-primary" style="width:70%;">
    <div class="panel-heading">
        <h3 class="panel-title" style='display:inline-block;'><a href="{% url 'recipes:view_recipe' recipe.id %}">{{recipe.title}}</a></h3><button type="button" class="btn btn-default btn-xs col-md-offset-1">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>{{recipe.favorites.all |length}}
</button>
        <h3 class="panel-title pull-right" style='display:inline-block;'><a href="{% url 'recipes:userrecipes' recipe.author.id %}">Created By: {{recipe.author.u_name}}</a></h3>
    </div>
    <div class="panel-body">
        <h5>Description: </h5>
        <p class='col-md-offset-1'>{{recipe.desc}}</p>
        <h6 class='col-md-offset-10'>
    {% if recipe.isprivate == True %}
    This Recipe is private.
    {%endif%}</h6> {%if user not in recipe.favorites.all%}
        <a href="{% url 'recipes:buttons' button=1 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Add to Favs
</button></a> {%else%}
        <a href="{% url 'recipes:buttons' button=2 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Remove from  Favs
  </button></a> {%endif%} {%if request.session.user.id == recipe.author.id%}

        <a href="{% url 'recipes:buttons' button=3 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
  <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Make Private
</button></a>
        <a href="{% url 'recipes:buttons' button=4 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Make Public
</button></a> {%endif%}

    </div>
</div>

{%endfor%} {%endif%}
{% include 'recipes/pagination.html' with page=recipes %}

 {%endblock%}

apps/recipes/templates/recipes/myaccount.html
{% extends 'recipes/base.html'%}
{% block account%}
  <li class='active'><a href="{% url 'recipes:myaccount' %}" >My Account</a></li>
  {%endblock%}
{%block content%}
My account page
Edit your information here!
<form class="form-horizontal " style='padding-top: 30px;' method="POST" action="{% url 'login:edit_user' %}" >
  {% csrf_token %}
  <div class="form-group">
    <label class="col-sm-2 control-label">First Name</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" name='f_name' placeholder="Change First Name">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Last Name</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" name='l_name' Placeholder="Change Last name">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Email</label>
    <div class="col-sm-2">
      <input type="email" class="form-control" name='email' Placeholder="Change Email here">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Zip Code</label>
    <div class="col-sm-2">
      <input type="number" min='00501' max='99950' class="form-control" name='zip' Placeholder="Change Zip Code">
    </div>
  </div>
  <div class="form-group">
    <label  class="col-sm-2 control-label">Change Password</label>
    <div class="col-sm-2">
      <input type="password" class="form-control" name='password' placeholder=" Change Password">
    </div>
  </div>
  <div class="form-group">
    <label  class="col-sm-2 control-label">Confirm Password</label>
    <div class="col-sm-2">
      <input type="password" class="form-control" name='repass' placeholder=" Confirm  New Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Edit details</button>
    </div>
  </div>
</form>

<form class="form-horizontal " style='padding-top: 30px;' method="POST" action="{% url 'recipes:top_fav' %}" >
  {% csrf_token %}
  <div class="form-group">
    <label class="col-sm-2 control-label">Top Recipe 1</label>
    <div class="col-sm-2">
      <select class="form-control" name="item1">
        {%if top_fav.0%}
        <option value="{{top_fav.0.id}}" >{{top_fav.0.title}}</option>
        {%else%}
      <option value="" disable selected disabled="disable" >--select one--</option>
      {%endif%}
      {%for recipe in recipes%}
      <option value='{{recipe.id}}'>{{recipe.title}}</option>
      {%endfor%}
    </select>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Top Recipe 2</label>
    <div class="col-sm-2">
      <select class="form-control" name="item2">
        {%if top_fav.1%}
        <option value="{{top_fav.1.id}}" >{{top_fav.1.title}}</option>
        {%else%}
      <option value="" disable selected disabled="disable" >--select one--</option>
      {%endif%}
      {%for recipe in recipes%}
      <option value='{{recipe.id}}'>{{recipe.title}}</option>
      {%endfor%}
    </select>
    </div>
  </div><div class="form-group">
    <label class="col-sm-2 control-label">Top Recipe 3</label>
    <div class="col-sm-2">
      <select class="form-control" name="item3">
        {%if top_fav.2%}
        <option value="{{top_fav.2.id}}" >{{top_fav.2.title}}</option>
        {%else%}
      <option value="" disable selected disabled="disable" >--select one--</option>
      {%endif%}
      {%for recipe in recipes%}
      <option value='{{recipe.id}}'>{{recipe.title}}</option>
      {%endfor%}
    </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save top recipes</button>
    </div>
  </div>
</form>


{%endblock%}

apps/recipes/templates/recipes/pagination.html
<nav aria-label='Page navigation'>
	{% if page.has_other_pages%}
		<ul class= 'pagination'>
			{%if page.has_previous%}
				<li><a aria-label='Previous' href="?page={{page.previous_page_number}}">&laquo;</a></li>
			{%else%}
			<li class='disabled'><span>&laquo;</span></li>
			{%endif%}
			{% for pages in page.paginator.page_range %}
			{%if page.number == pages %}
			<li class='active'><span>{{pages}}<span class='sr-only'>(current)</span></span></li>

			{%else%}
			<li><a href='?page={{pages}}'>{{pages}}</a></li>
			{%endif%}

			{% endfor %}
			{%if page.has_next%}
			<li><a href='?page={{page.next_page_number}}'>&raquo;</a></li>
			{%else%}
			<li class='disabled'><span>&raquo;</span</li>
			{%endif%}
		</ul>
	{%endif%}
</nav>

apps/recipes/templates/recipes/user.html
{% extends 'recipes/base.html'%}

{%block recipe%}
<li class='active'><a href="{% url 'recipes:add_recipe'%}">My Recipes</a></li>
{%endblock%}

{%block content%}
<h2>{{user.u_name}}'s Recipes!</h2>


{%endblock%}

apps/recipes/templates/recipes/user_favs.html
{% extends 'recipes/base.html'%}

{%block myrecipe%}
<li class='active'><a href="{% url 'recipes:userrecipes' u_id=request.session.user.id %}">My Recipes</a></li>
{%endblock%}

{%block content%}
<h2 style=>{{user.u_name}}'s Recipes!</h2>
<ul class='nav nav-tabs' style='width:70%;'>
  <li role='presentation' > <a href="{% url 'recipes:userrecipes' user.id %}">User's Recipes</a></li>
  <li role='presentation' class='active'> <a href="{% url 'recipes:userfavs' user.id %}">User's Favorites</a></li>
</ul>

{%if recipes%}
{%for recipe in recipes%}
{%if recipe.isprivate == False or recipe.isprivate == True and request.session.user.id == recipe.author.id %}




<div class="panel panel-default panel panel-primary" style="width:70%;">
  <div class="panel-heading">
    <h3 class="panel-title" style='display:inline-block;'><a href="{% url 'recipes:view_recipe' recipe.id %}">{{recipe.title}}</a></h3><button type="button" class="btn btn-default btn-xs col-md-offset-1">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>{{recipe.favorites.all |length}}
</button>
    <h3 class="panel-title pull-right" style='display:inline-block;'><a href="{% url 'recipes:userrecipes' recipe.author.id %}">Created By: {{recipe.author.u_name}}</a></h3>
  </div>
  <div class="panel-body">
    <h5>Description: </h5>
      <p class='col-md-offset-1'>{{recipe.desc}}</p>


    <h6 class='col-md-offset-10'>
    {% if recipe.isprivate == True %}
    This Recipe is private.
    {%endif%}</h6>
    {%if user not in recipe.favorites.all%}
    <a href="{% url 'recipes:buttons' button=1 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Add to Favs
</button></a>
  {%else%}
  <a href="{% url 'recipes:buttons' button=2 r_id=recipe.id %}"><button type="button" class="btn btn-default btn-xs pull-left">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Remove from  Favs
  </button></a>

    {%endif%}



    {%if request.session.user.id == recipe.author.id%}

    <a href="{% url 'recipes:buttons' button=3 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
  <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Make Private
</button></a>
<a href="{% url 'recipes:buttons' button=4 r_id=recipe.id %}"><button type="submit" class="btn btn-default btn-xs pull-right" aria-label="Left Align">
<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Make Public
</button></a>
{%endif%}

  </div>
</div>
{%endif%}
{%endfor%}
{%endif%}

{% include 'recipes/pagination.html' with page=recipes %}


{%endblock%}