DinnerDeals/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.login.models import User
from apps.recipes.models import Recipes, Ingredients

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(User, UAdmin)

class RecipeAdmin(admin.ModelAdmin):
    pass
admin.site.register(Recipes, RecipeAdmin)

class IngredientAdmin(admin.ModelAdmin):
    pass
admin.site.register(Ingredients, IngredientAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^user/', include('apps.recipes.urls', namespace='user')),
    url(r'^shop/', include('apps.shopping.urls', namespace='shop')),
    url(r'^main/', include('apps.recipes.urls', namespace='recipes')),
    url(r'^', include('apps.login.urls', namespace='login')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.splash, name='splash'),
    url(r'^login_page$', views.login_page, name='login_page'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^create_user$', views.create_user, name='create_user'),
    url(r'^edit_user$', views.edit_user, name='edit_user'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt
from django.core.exceptions import ObjectDoesNotExist
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def user_validate(self,data):
        errors=[]
        self.user_check(data['u_name'],errors)
        self.pass_val(data['password'],errors)
        if errors:
            return errors
        try:
            user= self.get(u_name=data['u_name'].title())
            print user.u_name
            if bcrypt.hashpw(data['password'].encode(),user.password.encode())==user.password.encode():
                return (False,user)
            else:
                errors.append('User name and/or password is incorrect')
                return errors
        except ObjectDoesNotExist:
            errors.append('User name and/or password is incorrect')
            return errors

    def reg_validate(self,data):
        errors=[]
        users=self.all()
        for user in users:
            if data['email'].title()==user.email:
                errors.append('Email address taken')
                break
        for user in users:
            if data['u_name'].title()==user.u_name:
                errors.append('Username already taken')
                break

        self.f_name_check(data['f_name'],errors)
        self.l_name_check(data['l_name'],errors)
        self.email_check(data['email'],errors)
        self.user_check(data['u_name'],errors)
        self.zip_check(data['zip'],errors)
        self.pass_check(data['password'], data['repass'],errors)
        self.pass_val(data['password'],errors)
        return errors
    def edit_user(self,data):
        errors=[]
        changes={

        }

        if data['f_name']:
            self.f_name_check(data['f_name'],errors)
            changes['f_name']=data['f_name'].title()
        if data['l_name']:
            self.l_name_check(data['l_name'],errors)
            changes['l_name']=data['l_name'].title()
        if data['email']:
            self.email_check(data['email'],errors)
            users=self.all()
            for user in users:
                if data['email'].title()==user.email:
                    errors.append('Email address taken')
                    break
            changes['email']=data['email'].title()
        if data['zip']:
            self.zip_check(data['zip'],errors)
            zip_code=data['zip'].zfill(5)
            changes['z_code']=data['zip']

        if data['password']:
            self.pass_val(data['password'],errors)
            self.pass_check(data['password'], data['repass'],errors)
            hashed_pw=bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            changes['password']=hashed_pw
        return errors, changes



    def f_name_check(self,f_name, errors):
            if len(f_name)<2:
                errors.append('First name too short. Enter a valid name.')
            return self
    def l_name_check(self,l_name, errors):
            if len(l_name)<1:
                errors.append('Last name too short. Enter a valid name.')
            return self
    def email_check(self,email, errors):
            if not re.match(EMAIL_REGEX, email):
                errors.append("Email is not a valid address. Please try again")
            return self
    def user_check(self,user, errors):
        if len(user)<5:
            errors.append('User Name must be at least 5 characters long')
            return self
    def zip_check(self,zip_code, errors):
        if zip_code < '00501' or zip_code >'99951':
            errors.append('Not a valid zip code.')
            return self
    def pass_check(self, password, repass, errors):
        if password!= repass:
            errors.append('Passwords do not match.Pease try again')
            return self
    def pass_val(self, password, errors):
        if len(password)<6:
            errors.append('Password not long enough. Password must be at least 6 characters')
            return self
    def create_user(self,data):
        hashed_pw=bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
        zip_code=data['zip'].zfill(5)
        self.create(f_name=data['f_name'].title(), l_name=data['l_name'].title(),u_name=data['u_name'].title(), email=data['email'].title(), password=hashed_pw, z_code=zip_code)
class User(models.Model):
    f_name=models.CharField(max_length=40)
    l_name=models.CharField(max_length=40)
    u_name=models.CharField(max_length=30)
    email=models.EmailField(max_length=200)
    password=models.CharField(max_length=255)
    z_code=models.CharField(max_length=5)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects=UserManager()

# Create your models here.

apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages



# Create your views here.
def splash (request):
    context={
    }
    return render(request, 'login/base.html', context)
def login_page (request):
    return render(request, 'login/login.html')

def login (request):
    results=User.objects.user_validate(request.POST)
    if results[0]:
        for error in results:
            messages.error(request, error, extra_tags='danger')
        return redirect ('login:login_page')
    else:

        request.session['user']={
        'id':results[1].id,
        'u_name':results[1].u_name
        }
        messages.success(request,"You logged in successfully")
    return redirect('recipes:splash')
def register(request):
    return render (request, 'login/register.html')
def create_user(request):

    errors= User.objects.reg_validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error, extra_tags='danger')
        return redirect('login:register')
    User.objects.create_user(request.POST)
    messages.success(request, 'Successfully registered!')
    user=User.objects.get(u_name=request.POST['u_name'].title())
    request.session['user']={
    'id':user.id,
    'u_name':user.u_name
    }
    return redirect('recipes:splash')
def edit_user(request):
    changes=User.objects.edit_user(request.POST)
    if changes[0]:
        for error in changes:
            messages.error(request, error, extra_tags='danger')
        return redirect('recipes:myaccount')
    User.objects.filter(id=request.session['user']['id']).update(**changes[1])
    messages.success(request, 'successfully update user info.')
    return redirect('recipes:splash')
def logout(request):
    request.session.flush()
    messages.success(request, 'Successfully logged out!')
    return redirect('login:splash')

apps/login/templates/login/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset="utf-8">
    <title>Dinner Deals</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    {% load staticfiles %}
<link rel="stylesheet" href="{% static 'login/css/main.css' %}"media="screen" title="no title"  charset="utf-8">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body style='padding-top: 120px;'>

        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
          <div class="container">

            <a href="{% url 'login:splash' %}">
                <p class="navbar-text">Home</p>
            </a>
            <a href="{% url 'login:login_page' %}">
                <p class="navbar-text">Sign In</p>
            </a>
            <div class="login_form col-md-offset-6">
                <form class="navbar-form navbar-left" role="login" action ="{% url 'login:login' %}"method="POST">
                    {%csrf_token%}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <div class="form-group">
                        <input type="text" class="form-control" name='u_name' placeholder="Username">
                        <input type="password" class="form-control" name='password' placeholder="password">
                    </div>
                </form>
                <a href="{% url 'login:register' %}">
                    <p class="navbar-text col-md-offset-1">New User? Click here to sign up!</p>
                </a>
            </div>
            </div>
        </nav>
        <div class="content" id='images'>
        {%if messages%}
        {%for message in messages%}
        <li class="alert alert-{{message.tags}}" role="alert">{{message}}</li>
        {%endfor%}
        {%endif%}
        <div class="block col-md-offset-1" style='padding-top:200px;'>
           {%block content%}<h1 style='color:black; font-size:5em;background-color:rgb(218, 203, 181);opacity:0.6;width:80%;border:1px solid rgb(188, 171, 146);border-radius:10px'>Welcome to Dinner Deals</h1>
           <h4 style='margin-top:120px;color:black; margin-left:30px; background-color:rgb(218, 203, 181);opacity:0.8;width:60%;border:1px solid rgb(188, 171, 146);border-radius:10px;padding:5px;'><p> Dinner Deals is a one stop center for all your recipe needs.</p>
           <p>You can add recipes, views recipes from others and even find where to go when shopping for your ingredients</p>
           <p>Sign in or Register to continue!</p></h4>{%endblock%}
        </div>
      </div>

</body>

</html>

apps/login/templates/login/login.html
    {% extends 'login/base.html'%}
  {%block content%}
  <div style='background-color:rgb(218, 203, 181);opacity:0.9;width:40%;border:1px solid rgb(188, 171, 146);border-radius:10px'>
  <form class="form-horizontal" action ="{% url 'login:login' %}" style='padding-top: 30px;' method="POST" >
    {% csrf_token %}
    <div class="form-group">
      <label class="col-sm-4 control-label">First Name</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name='u_name' placeholder="Username">
      </div>
    </div>
    <div class="form-group">
      <label  class="col-sm-4 control-label">Password</label>
      <div class="col-sm-4">
        <input type="password" class="form-control" name='password' placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </div>
  </form>
  </div>
  {%endblock%}

apps/login/templates/login/register.html
    {% extends 'login/base.html'%}
  {%block content%}
  <div style='background-color:rgb(218, 203, 181);opacity:0.9;width:40%;border:1px solid rgb(188, 171, 146);border-radius:10px;'>

  <form class="form-horizontal" style='padding-top: 30px;' method="POST" action="{%url 'login:create_user' %}">
    {% csrf_token %}
    <div class="form-group">
      <label class="col-sm-3 control-label">First Name</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name='f_name' placeholder="First Name">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Last Name</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name='l_name' placeholder="Last Name">
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Username</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name='u_name' placeholder='Username'>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Email</label>
      <div class="col-sm-4">
        <input type="email" class="form-control" name='email' placeholder='Email address'>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Zip Code</label>
      <div class="col-sm-4">
        <input type="number" min='00501' max='99950' class="form-control" name='zip' placeholder="Zip Code">
      </div>
    </div>
    <div class="form-group">
      <label  class="col-sm-3 control-label">Password</label>
      <div class="col-sm-4">
        <input type="password" class="form-control" name='password' placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <label  class="col-sm-3 control-label">Confirm Password</label>
      <div class="col-sm-4">
        <input type="password" class="form-control" name='repass' placeholder=" Confirm Password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-10">
        <button type="submit" class="btn btn-default">Register</button>
      </div>
    </div>
  </form>
</div>
  {%endblock%}