DinnerDeals/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.login.models import User
from apps.recipes.models import Recipes, Ingredients

class UAdmin(admin.ModelAdmin):
    pass
admin.site.register(User, UAdmin)

class RecipeAdmin(admin.ModelAdmin):
    pass
admin.site.register(Recipes, RecipeAdmin)

class IngredientAdmin(admin.ModelAdmin):
    pass
admin.site.register(Ingredients, IngredientAdmin)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^user/', include('apps.recipes.urls', namespace='user')),
    url(r'^shop/', include('apps.shopping.urls', namespace='shop')),
    url(r'^main/', include('apps.recipes.urls', namespace='recipes')),
    url(r'^', include('apps.login.urls', namespace='login')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.splash, name='splash'),
    url(r'^login_page$', views.login_page, name='login_page'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^create_user$', views.create_user, name='create_user'),
    url(r'^edit_user$', views.edit_user, name='edit_user'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/recipes/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.splash, name='splash'),
    url(r'^my_account/$', views.myaccount, name='myaccount'),
    url(r'^add_recipe/$', views.add_recipe, name='add_recipe'),
    url(r'^create_recipe/$', views.create_recipe, name='create_recipe'),
    url(r'^init$', views.first_time, name='first'),
    url(r'^new$', views.new, name='new'),
    url(r'^user/(?P<u_id>\d+)$', views.user, name='userrecipes'),
    url(r'^userfavs/(?P<u_id>\d+)$', views.user_favs, name='userfavs'),
    url(r'^user/view_recipe/(?P<r_id>\d+)/$', views.view_recipe, name='view_recipe'),
    url(r'^user/button/(?P<button>\d+)/(?P<r_id>\d+)/$', views.buttons, name='buttons'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^top_fav/$', views.top_fav, name='top_fav'),
    ]

apps/shopping/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.search, name='search'),
    url(r'^zipsearch$', views.zipsearch, name='zipsearch'),
    url(r'^store$', views.store, name='found'),
    url(r'^multi$', views.multi, name='multi'),
    url(r'^displayrecipe$', views.displaysingle, name='single'),


] 

apps/shopping/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/shopping/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from xml.dom.minidom import parse, parseString
from xmljson import badgerfish as bf
from xml.etree.ElementTree import fromstring
from ..login.models import User
from ..recipes.models import Recipes, Ingredients
from json import dumps
import json
import requests
import re
import xml.etree.cElementTree as et
# Create your views here.

def idCheck(request):
    if 'user' not in request.session:
        messages.add_message(request, messages.ERROR, 'Please login to continue.')
        return False
    else:
        return True

def search(request):
    idCheck(request)
    if 'zip' not in request.session:
        user=User.objects.get(id=request.session['user']['id'])
        request.session['zip']=user.z_code
    return render(request, 'shopping/search.html')

def multi(request):
    pass

def displaysingle(request):

    r_id=request.POST['recipes']
    print r_id
    recipe=Recipes.objects.filter(id=r_id)[0]
    context=[]
    title=recipe.title+'|'
    context.append(title)
    fullingredients=Ingredients.objects.filter(recipe_ing=recipe)
    for items in fullingredients:
        context.append(items.name+' | ')
        context.append(items.itemid+' | ')
        if items.itemid == 'NOITEM':
            context.append(' A water tap | ')
            context.append(' You have water at home, right? | ')
        else:
            url='http://www.SupermarketAPI.com/api.asmx/SearchForItem?APIKEY=6af0d05f87&StoreId='+request.session['storeid']+'&ItemName='+items.itemid
            product=requests.get(url).content
            product=re.sub(' xmlns="[^"]+"', '', product, count=1)
            product=dumps(bf.data(fromstring(product)))
            pdata=json.loads(product)
            print pdata
            print url
            try:
                context.append(pdata['ArrayOfProduct']['Product']['AisleNumber']['$'] + ' |')
                context.append(pdata['ArrayOfProduct']['Product']['ItemCategory']['$'] + ' |')
            except:
                context='Looks like there was an error with the items returned. Please try another recipe.'
                return HttpResponse(context)
    return HttpResponse(context)

def zipsearch(request):
    request.session['zip']=request.POST['zip']
    zipp=request.POST['zip']
    stores={}
    url='http://www.SupermarketAPI.com/api.asmx/StoresByZip?APIKEY=6af0d05f87&ZipCode='+str(zipp)
    stores=requests.get(url).content
    stores=re.sub(' xmlns="[^"]+"', '', stores, count=1)
    stores=dumps(bf.data(fromstring(stores)))

    return HttpResponse(stores)

def store(request):
    idCheck(request)
    if not request.POST and 'storeid' not in request.session:
        return redirect(reverse('shop:search'))
    if 'storeid' not in request.session:
        request.session['storeid']=request.POST['storeid']
    context={
    'storeid':request.session['storeid'],
    'recipes':Recipes.objects.filter(author=User.objects.get(id=request.session['user']['id'])) | Recipes.objects.filter(favorites=User.objects.get(id=request.session['user']['id'])),
    }
    return render(request, 'shopping/singleshop.html', context)

apps/shopping/templates/shopping/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% load staticfiles %}
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'shopping/css/main.css' %}"media="screen" title="no title"  charset="utf-8">
  <title>{%block title%}{%endblock%}</title>
</head>
<body style='padding: 100px 50px;' }>
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" >
<div class="container"><!-- Nav tabs -->
<ul class="nav navbar-nav">
  {%block home%}<li><a href="{% url 'recipes:splash' %}">Home</a></li>{%endblock%}
  {%block shop%}<li><a href="{% url 'shop:search'%}" >Go Shopping</a></li>{%endblock%}
  {%block recipe%}<li><a href="{% url 'recipes:add_recipe'%}">Add a Recipe</a></li>{%endblock%}
  {%block myrecipe%}<li><a href="{% url 'recipes:userrecipes' u_id=request.session.user.id %}">My Recipes</a> {% endblock %}
  {%block browse%}<li><a href="{% url 'recipes:browse' %}">Browse</a> {% endblock %}
  {%block account%}<li><a href="{% url 'recipes:myaccount' %}" >My Account</a></li>{%endblock%}

  <li><a class='.navbar-right'href="{% url 'login:logout'%}" >Logout</a></li>


</ul>
{% block zip%}

                  {% endblock %}
              </div>

          </nav>

        {%block content%}{%endblock%}

      </body>


      <script>
      {%block script%}{%endblock%}
      </script>

apps/shopping/templates/shopping/search.html
{% extends 'shopping/base.html' %}

{%block shop%}<li class='active'><a href="{% url 'shop:search'%}" >Go Shopping</a></li>{%endblock%}
{% block zip %}
<form class="navbar-form navbar-right" action='./zipsearch' method='post' id='zipfind' role="search">
    {%csrf_token%}
    <div class="form-group">
        <input type="text" name='zip' class="form-control" placeholder="Zip Code" value={{request.session.zip}}>

    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <p>94538 is working</p>
</form>
{%endblock%}

{%block content%}
<form action="{% url 'shop:found' %}" method='post'>
{%csrf_token%}
<div id="results">
<div class="jumbotron" style='border-radius:10px; padding:2em;'>
  <h1>Lets find a store!</h1>
  <p>Please use the search function above to find the store nearest you.</p>
</div>
</div>
</form>
<div id='modal' class="modal fade bs-example-modal-sm" style='top:50%;' tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <p>Sorry! Looks like there are no stores in the database for your zipcode. Please try another.</p>
    </div>
  </div>
</div>
{%endblock content%}

{%block script%}

$('#zipfind').submit(function() {
  $.post($(this).attr('action'), $(this).serialize(), function(res){
    console.log('the response object:');
    console.log(res);
    try{
      console.log(res.ArrayOfStore.Store[0])
    }
    catch(err){
      $('#modal').modal('toggle');
      return false;
    }
    var htmlstr='';
    var htmlstr2='';
    console.log('Array?');
    console.log(res.ArrayOfStore.Store);
    res=res.ArrayOfStore.Store;
    console.log(res[0]);
    for( var i=0;i< res.length; i++){
      htmlstr += '<div class="store"><ul>';
      htmlstr += '<li><h3>Store Name: ' + res[i].Storename.$ + '</h3></li>';
      htmlstr += '<li><p>City: '+ res[i].City.$ + '</p></li>';
      htmlstr += '<li><p>State: '+ res[i].State.$ + '</p></li>';
      htmlstr += '<li><p>Zip Code: '+ res[i].Zip.$ + '</p></li>';
      htmlstr += '<li><input type="radio" value="'+ res[i].StoreId.$ + '" name="storeid"> Select this store</li>';
      htmlstr += '</ul></div>';
    }
    htmlstr2 = '<input type="submit" class="btn btn-primary" value="Use this">';
    console.log(htmlstr);
    $('#results').html(htmlstr);
    $('#results').after(htmlstr2);
  }, 'json');
  return false;
});


{%endblock script%}

apps/shopping/templates/shopping/singleshop.html
{% extends 'shopping/base.html' %}
{%block shop%}<li class='active'><a href="{% url 'shop:search'%}" >Go Shopping</a></li>{%endblock%}
{%block content%}
<div class="row">
  <form action="./displayrecipe" name='display' method='post' id='recipes'>
    {%csrf_token%}
<ul style='list-style:none;'>
  <li style='display:inline;'><select class='.col-md6'  name="recipes" id='recipeselect' >
    <option value="" disable selected disabled="disable">--Select One--</option>
    {% for items in recipes %}
    <option value="{{items.id}}">{{items.title}}</option>
    {% endfor %}
  </select></li>
  <li style=' display:inline;'><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">Shopping for more than one recipe? Click here!</button></li>
</ul>
</form>
</div>
<div class="row">
  <div id="results">
    {% load staticfiles %}
    </div>
  <div id="loading-image" style='display:none;'><img style='height:200px; width:200px; position:relative; top:5em; left:5em;' src="{% static 'shopping/img/loading.gif' %}" alt="load"></div>

</div>
<div id='modal' class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <p>Sorry! We don't quite have this implimented yet. Please check back with us in the future!</p>
    </div>
  </div>
</div>


{%endblock content%}

{%block script%}
$('#recipes').on('change', function(){
  console.log('clicked recipe');
  $('#results').hide()
  $('#loading-image').show();

  $.ajax({
    url: $(this).attr('action'),
    method: 'POST',
    data: $(this).serialize(),
    success: function(res){
      if (res=='error'){
        $('#modal').modal('toggle');
        return false;
      }
      var htmlstr='';
      console.log('results:');
      console.log(res);
      table=res.split('|');
      console.log(table)
      htmlstr +='<div class="recipe col-md-10" style="padding:10px;"><ul style="list-style:none;"><li><h2>'+table[0]+'</h2></li><table class="table table-striped" style="border:2px solid whitesmoke;">';
      for (i=1;i<table.length-1;i+=4){
        htmlstr +='<tr><div class="input-group"><td><input class="ing_list" type="checkbox" name="ingredients" value="'+table[i+1]+'"></td><td>'+table[i]+'</td><td>Located in '+table[i+2]+'</td><td>Category : '+table[i+3]+'</td></div></tr>';
      };
      htmlstr +='</table></ul></div>';
      $('#results').html(htmlstr);
    },
      complete: function(){
      $('#loading-image').hide();
      $('#results').show()
    },
  });
    return false;
  });

function completeAlert(){
  alert("Youve picked everything up! Choose a new recipe if you'd like to continue.");
  return True;
};

var count =0;
$(document).on('click', ".ing_list", function(){
  var items= $('.ing_list').length
  if($(".ing_list").is(":checked")){
    count++
    console.log(count)
    if (count==items){
      alert("Youve picked everything up! Choose a new recipe if you'd like to continue.");
      count=0

    }


  }

});


{%endblock script%}